matrix:
  include:
    - language: go

      before_script:
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

      branches:
        only: master

      dist: bionic

      git:
        depth: 1

      go: 1.13.x

      notifications:
        email: true

      script:
        - cd $TRAVIS_BUILD_DIR/src
        - golangci-lint run
        - go test -v src/main.go src/main_test.go
        - GOOS=linux go build -ldflags="-s -w" -o bin/mailsender src/main.go
