matrix:
  include:
    - language: go

      before_script:
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

      branches:
        only: master

      dist: bionic

      git:
        depth: 1

      go: 1.14.x

      notifications:
        email: false

      script:
        - cd $TRAVIS_BUILD_DIR/
        - golangci-lint run
        - go test -cover -v sender/sender.go sender/sender_test.go
        - go test -cover -v parser/parser.go parser/parser_test.go
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/mailsender sender/sender.go
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/recipientparser parser/parser.go
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags="-s -w" -o bin/mailsender.exe sender/sender.go
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags="-s -w" -o bin/recipientparser.exe parser/parser.go
